#spring:
#  cloud:
#    stream:
#      binders:
#        local_rabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: 127.0.0.1
#                port: 5672
#                username: admin
#                password: 123456
#      bindings:
#        input:
#          destination: default.message
#          binder: local_rabbit
#        output:
#          destination: default.message
#          binder: local_rabbit
server:
  port: 4400