server:
  port: 10086
spring:
  application:
    name: pactera-eureka-server
eureka:
  client:
#    register-with-eureka: false #是否注册自己的信息到Eureka中心, 单点的时候设置为 false 禁止注册自身
    fetch-registry: true #是否拉取其他服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true #默认false   使用ip地址作为注册中心的地址
    lease-expiration-duration-in-seconds: 90 #服务失效时间，默认值90秒
    lease-renewal-interval-in-seconds: 30 #服务续约(renew)的间隔，默认为30秒
  server:
    enable-self-preservation: false # 关闭自我保护模式（缺省为打开
    eviction-interval-timer-in-ms: 1000 # 扫描失效服务的间隔时间（缺省为60*1000ms）